export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
    REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
    ADD_TO_CART: "ADD_TO_CART",
    DELETE_PRODUCT: "DELETE_PRODUCT",
    CHECKOUT_PRODUCT: "CHECKOUT_PRODUCT",
    SET_SHIPPING_DATA:"SET_SHIPPING_DATA",
    SET_SHIPPING_METHOD:"SET_SHIPPING_METHOD",
    SET_PAYMENT_INFO:"SET_PAYMENT_INFO"


};